config/routes.rb
WiFiFoFumMapper::Application.routes.draw do
  resources :access_points

end

app/models/access_point.rb
class AccessPoint < ActiveRecord::Base
  attr_accessible :ap_type, :channel, :encryption_type, :first_seen, :last_seen, :mac, :ssid, :strength
end

app/controllers/access_points_controller.rb
class AccessPointsController < ApplicationController
  # GET /access_points
  # GET /access_points.json
  def index
    @access_points = AccessPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @access_points }
    end
  end

  # GET /access_points/1
  # GET /access_points/1.json
  def show
    @access_point = AccessPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @access_point }
    end
  end

  # GET /access_points/new
  # GET /access_points/new.json
  def new
    @access_point = AccessPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @access_point }
    end
  end

  # GET /access_points/1/edit
  def edit
    @access_point = AccessPoint.find(params[:id])
  end

  # POST /access_points
  # POST /access_points.json
  def create
    @access_point = AccessPoint.new(params[:access_point])

    respond_to do |format|
      if @access_point.save
        format.html { redirect_to @access_point, notice: 'Access point was successfully created.' }
        format.json { render json: @access_point, status: :created, location: @access_point }
      else
        format.html { render action: "new" }
        format.json { render json: @access_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /access_points/1
  # PUT /access_points/1.json
  def update
    @access_point = AccessPoint.find(params[:id])

    respond_to do |format|
      if @access_point.update_attributes(params[:access_point])
        format.html { redirect_to @access_point, notice: 'Access point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @access_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /access_points/1
  # DELETE /access_points/1.json
  def destroy
    @access_point = AccessPoint.find(params[:id])
    @access_point.destroy

    respond_to do |format|
      format.html { redirect_to access_points_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/access_points_helper.rb
module AccessPointsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access_points/_form.html.erb
<%= form_for(@access_point) do |f| %>
  <% if @access_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access_point.errors.count, "error") %> prohibited this access_point from being saved:</h2>

      <ul>
      <% @access_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ssid %><br />
    <%= f.text_field :ssid %>
  </div>
  <div class="field">
    <%= f.label :mac %><br />
    <%= f.text_field :mac %>
  </div>
  <div class="field">
    <%= f.label :channel %><br />
    <%= f.text_field :channel %>
  </div>
  <div class="field">
    <%= f.label :strength %><br />
    <%= f.text_field :strength %>
  </div>
  <div class="field">
    <%= f.label :encryption_type %><br />
    <%= f.text_field :encryption_type %>
  </div>
  <div class="field">
    <%= f.label :ap_type %><br />
    <%= f.text_field :ap_type %>
  </div>
  <div class="field">
    <%= f.label :first_seen %><br />
    <%= f.datetime_select :first_seen %>
  </div>
  <div class="field">
    <%= f.label :last_seen %><br />
    <%= f.datetime_select :last_seen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/access_points/edit.html.erb
<h1>Editing access_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @access_point %> |
<%= link_to 'Back', access_points_path %>

app/views/access_points/index.html.erb
<h1>Listing access_points</h1>

<table>
  <tr>
    <th>Ssid</th>
    <th>Mac</th>
    <th>Channel</th>
    <th>Strength</th>
    <th>Encryption type</th>
    <th>Ap type</th>
    <th>First seen</th>
    <th>Last seen</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Altitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @access_points.each do |access_point| %>
  <tr>
    <td><%= access_point.ssid %></td>
    <td><%= access_point.mac %></td>
    <td><%= access_point.channel %></td>
    <td><%= access_point.strength %></td>
    <td><%= access_point.encryption_type %></td>
    <td><%= access_point.ap_type %></td>
    <td><%= access_point.first_seen %></td>
    <td><%= access_point.last_seen %></td>
    <td><%= access_point.latitude %></td>
    <td><%= access_point.longitude %></td>
    <td><%= access_point.altitude %></td>
    <td><%= link_to 'Show', access_point %></td>
    <td><%= link_to 'Edit', edit_access_point_path(access_point) %></td>
    <td><%= link_to 'Destroy', access_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Access point', new_access_point_path %>

app/views/access_points/new.html.erb
<h1>New access_point</h1>

<%= render 'form' %>

<%= link_to 'Back', access_points_path %>

app/views/access_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ssid:</b>
  <%= @access_point.ssid %>
</p>

<p>
  <b>Mac:</b>
  <%= @access_point.mac %>
</p>

<p>
  <b>Channel:</b>
  <%= @access_point.channel %>
</p>

<p>
  <b>Strength:</b>
  <%= @access_point.strength %>
</p>

<p>
  <b>Encryption type:</b>
  <%= @access_point.encryption_type %>
</p>

<p>
  <b>Ap type:</b>
  <%= @access_point.ap_type %>
</p>

<p>
  <b>First seen:</b>
  <%= @access_point.first_seen %>
</p>

<p>
  <b>Last seen:</b>
  <%= @access_point.last_seen %>
</p>


<%= link_to 'Edit', edit_access_point_path(@access_point) %> |
<%= link_to 'Back', access_points_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WiFiFoFumMapper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>